// <auto-generated />
namespace MyFestival.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FinalDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinalDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201404300818006_FinalDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
